/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_svgroz_HelloWorld */

#ifndef _Included_org_svgroz_HelloWorld
#define _Included_org_svgroz_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_svgroz_HelloWorld
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_svgroz_HelloWorld_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
